language: java

jdk:
  - openjdk22

addons:
  sonarcloud:
    organization: "ilinandrey"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=IlinAndrey_pr1_ui -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'