version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout

      - run:
          name: Run Tests and Analyze on SonarCloud
          command: |
            mvn verify sonar:sonar -Dsonar.projectKey=IlinAndrey_pr1_ui
            mvn test

      - run:
          name: List Test Results Directories
          command: |
            echo "Listing test-results directory:"
            ls -R test-results
            echo "Listing jest directory:"
            ls -R test-results/jest
            echo "Listing mocha directory:"
            ls -R test-results/mocha
            echo "Listing rspec directory:"
            ls -R test-results/rspec

      - store_test_results:
          name: Store Jest Test Results
          path: test-results/jest

      - store_test_results:
          name: Store Mocha Test Results
          path: test-results/mocha

      - store_test_results:
          name: Store RSpec Test Results
          path: test-results/rspec

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
