version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=IlinAndrey_pr1_ui

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud