version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout

      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=IlinAndrey_pr1_ui

      - store_test_results:
          name: Store Jest Test Results
          path: test-results/jest

      - store_test_results:
          name: Store Mocha Test Results
          path: test-results/mocha

      - store_test_results:
          name: Store RSpec Test Results
          path: test-results/rspec

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
