version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:17.0'
    steps:
      - checkout

      - run:
          name: Create Test Results
          command: |
            mvn verify sonar:sonar -Dsonar.projectKey=IlinAndrey_pr1_ui
            mkdir -p test-results/jest
            echo "<testsuites></testsuites>" > test-results/jest/results.xml
            mkdir -p test-results/mocha
            echo "<testsuites></testsuites>" > test-results/mocha/results.xml
            mkdir -p test-results/rspec
            echo "<testsuites></testsuites>" > test-results/rspec/results.xml

      - run:
          name: List Test Results Directories
          command: |
            echo "Listing test-results directory:"
            ls -R test-results

      - store_test_results:
          name: Store Jest Test Results
          path: test-results/jest

      - store_test_results:
          name: Store Mocha Test Results
          path: test-results/mocha

      - store_test_results:
          name: Store RSpec Test Results
          path: test-results/rspec

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
